### ISSUE TITLE
'mc.cores' > 1 is not supported on Windows

### ISSUE THREAD

**Issue by Prooomise** [igrabski/sc-SHC#14]
Dear author:
 Thanks for developing scSHC! It's a useful tool!
 But I have met a problem when running the function "testClusters". 
 Here is the code I use: new_clusters <- testClusters(pbmc@assays$RNA@counts, as.character(pbmc$seurat_annotations), parallel=FALSE)
 And there is the error message: 
 Error in mclapply(1:10, function(i) { : 
   'mc.cores' > 1 is not supported on Windows
How can I fix this problem? Thanks a lot!

**Comment by richardmustaklem** [comment]
set cores=1 and that should do the fix

**Comment by igrabski** [comment]
Yes, please try setting cores=1 and see if that helps? In the meantime, I am planning to soon update the parallelization to an option that is supported by Windows!

**Comment by Prooomise** [comment]
Thanks for the reply!
The problem was successfully fixed when adding cores=1.
