### ISSUE TITLE
Finding scSHC optimal resolution?

### ISSUE THREAD

**Issue by richardmustaklem** [igrabski/sc-SHC#15]
Thanks for releasing this package to the public. I believe this is a great step in the right direction for the field! :) 
Your package states: "Our approach finds exactly the right number of clusters (2).." however if I'm not mistaken, we cannot view the resolution parameter. Is there a line of code where we can view the resolution at which you're getting these clusters at? 
For example, I can only view the scSHC clusters on a Umap but would like to see at which resolution your package is using to generate said clusters. 
Sorry if my question is unclear or confusing, thanks again! :)

**Comment by igrabski** [comment]
Hi Richard, thanks for the kind words and for trying out our package! I'm not sure if I understood your question correctly, but in our approach, we actually don't find an optimal resolution parameter. We either produce a set of clusters through our own clustering pipeline with built-in hypothesis testing (no resolution parameter needed), or we take a set of clusters from any algorithm, including e.g. the Louvain algorithm, and we test for how those clusters should be merged together, regardless of resolution parameter.

**Comment by richardmustaklem** [comment]
Thanks for the explanation. This solves my question.

For context, I was going to plot the scSHC clustering using Clustree() but the function cannot run without a resolution parameter within each input. Since scSHC doesn’t use resolution then that makes sense lol why they don't cooperate. Thanks again.
