### ISSUE TITLE
Cluster Number is Very Large

### ISSUE THREAD

**Issue by DarioS** [igrabski/sc-SHC#16]
I applied `scSHC` to the counts in the file `HNSCC_fibro_tumour.rds` contained in [scRNA-seq_dataobjects.zip](https://zenodo.org/record/7540604) from [a recent journal article](https://www.nature.com/articles/s41467-023-39762-1) and it estimated 116 clusters on default parameters, which is far too many.

**Comment by igrabski** [comment]
Hi Dario, do these data have any batch effect / multi-sample structure? If so, did you run clustering with `scSHC` or with `testClusters`?

**Comment by DarioS** [comment]
I don't think so. [Supplementary Figure 1e](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-023-39762-1/MediaObjects/41467_2023_39762_MOESM1_ESM.pdf) is "UMAP of CAF type assignment from raw, uncorrected scRNA-Seq data." and the clusters seem homogeneous to me, suggesting a lack of batch effect. I used function `scSHC`. Can you reproduce the result?

**Comment by igrabski** [comment]
Hmm, I was unable to reproduce your result. If you share your code (and especially your seed if you set one), I can take a look? I attached a screenshot of what I ran and the output:

<img width="473" alt="Screenshot 2023-09-14 at 4 22 34 PM" src="https://github.com/igrabski/sc-SHC/assets/56368234/c4a89010-32bd-441a-955b-0e8674679540">

**Comment by DarioS** [comment]
Sorry for the confusion. It happens with `BREAST_fibro_tumour.rds`, not with `HNSCC_fibro_tumour.rds`.

**Comment by igrabski** [comment]
Thanks for the clarification! I was able to reproduce your result. The number of clusters is reduced when specifying the batch label, but still seems higher than would be expected. I have not yet fully investigated these data, but the large number of clusters makes me suspect that perhaps the assumptions of the method do not hold here. In particular, we assume that within clusters, genes follow a unimodal distribution (specifically, Poisson-log normal); however, if there are cells where genes actually follow a multimodal distribution within a true cluster, then we will find too many clusters.
