### ISSUE TITLE
ATACseq support

### ISSUE THREAD

**Issue by gszeto0** [igrabski/sc-SHC#17]
First, thanks for a much-needed method for determining clustering significance. It's been super valuable for ongoing scRNAseq analysis.

Are you planning on extending and testing the method to other data types/dimensionality reductions? In particular, ATACseq would be quite valuable, but many methods use LSI for ATAC instead of PCA.

**Comment by igrabski** [comment]
Thanks so much for trying out our approach!

I think extending these ideas to other modalities and dimensionality reductions would be very interesting, but would require some relatively involved development (e.g. we would need a different underlying probabilistic model). I would be interested in these ideas in the future, but unfortunately we do not have current plans to do so now.
