### ISSUE TITLE
Clarification on "Single-Cell Significance of Hierarchical Clustering" Step in sc-SHC

### ISSUE THREAD

**Issue by lisch7** [igrabski/sc-SHC#18]
Hi sc-SHC team,

I find the sc-SHC project intriguing, but there's a particular step I'm unclear about, specifically in the "Single-Cell Significance of Hierarchical Clustering" phase. After computing the clusters, it's common practice to project them onto UMAP or t-SNE. Does this imply that we need to first undergo the standard Seurat process, and then map the results obtained from sc-SHC back to the Seurat object to achieve the clustering outcomes? I'd appreciate some guidance on whether this understanding is correct and if there are any additional steps or considerations involved.

Thank you for your assistance.

**Comment by igrabski** [comment]
Hi Lisch, yes, you can think of the UMAP/t-SNE visualization as a separate process from finding clusters. You can generate the UMAP/t-SNE through any preferred pipeline, including the standard Seurat process, and then visualize the clusters on that dimension reduction just as you would with any other aspect of metadata.
