### ISSUE TITLE
Compatibility with integration methods 

### ISSUE THREAD

**Issue by lucia-ramirez** [igrabski/sc-SHC#3]
Hi, I would like to use your algorithm but wanted to know the best practices for running it. Specifically, I have used SCVI to batch-correct my data, so I was wondering if the algorithm could use that or if I should I use counts and adjust for batch effect? 

Thanks!

**Comment by igrabski** [comment]
Thanks for your question! The input should always be counts, so in this case, I would recommend inputting the counts and using the batch effect option. Unfortunately, because of this requirement, our approach is generally not compatible with most integration methods.
