### ISSUE TITLE
Compatibility with spatially-aware clustering algorithms for spatial RNAseq?

### ISSUE THREAD

**Issue by berniejmulvey** [igrabski/sc-SHC#8]
I'm interested in trying this tool to cluster data from a novel tissue not profiled in humans before by scSeq or spatial techniques -- which we only have Visium data for. 

I would hypothetically like to run testClusters on clustering assignments previously made for Visium samples by a spatially-aware clustering algorithm, e.g., BayesSpace, where the user must manually specify the number of clusters to be returned, so as to get a more statistically grounded number of clusters to work with going forward.

Is there a (simple) way to pass in the spatial information to the testClusters function so that the significance testing is accounting for the spatial aspect of the original labels?

**Comment by igrabski** [comment]
Unfortunately our approach is currently not built to handle spatial data, so right now there wouldn't be any way to account for that aspect of the labels. For this reason, at this time, I wouldn't recommend applying our approach to cluster labels that come from a spatially-aware clustering algorithm. In the future, however, we may explore extensions to spatial data.
