### ISSUE TITLE
scSHC() and testClusters with PCs as input instead of gene expression

### ISSUE THREAD

**Issue by Dario-Rocha** [igrabski/sc-SHC#9]
I think this is a very interesting proposition.
I would like to implement your clustering method and/or your evaluation of cluster certainty on integrated datasets for which I have the batch-corrected PCA embeddings but not a batch-corrected expression matrix (because of method limitations and the sheer size such data would have). Even if it was possible to use a batch-correction method which provides batch-corrected gene expression, I would like to keep the integration and batch correction I've performed unchanged, therefore I wonder if your package could be extended to work with the batch-corrected PCA emeddings as starting point, instead of the gene expression matrix.

**Comment by igrabski** [comment]
Thanks for the suggestion! There are statistical advantages to operating on raw counts, but it is true that as a result, our methods are limited in how well they can interface with integration/batch-correction pipelines. There is actually some [recent work](https://www.tandfonline.com/doi/abs/10.1080/10618600.2023.2219708) outside of the single-cell context that has proposed a method for this type of input, which might be useful to check out!
